### ISSUE TITLE
Remove listActionTemplates from components

### ISSUE THREAD

**Issue by romgrk** [c3g/freezeman_web#8]
`fetchInitialData` already does it after logging in, the listActionTemplates calls can be removed from all components.

@jleblond you can do this if you have time after the other things you're working on

**Comment by arnab15** [comment]
Hello sir,
I have knowledge of Javascript node js, react js, MongoDB, Expressjs I want to contribute to this project but I'm new to the open-source community so sir how can I start can you help me to figure out how should I start.

**Comment by romgrk** [comment]
Hey @arnab15, thanks for the proposition but this is an internal tool that we use to track our samples, and even-though it's open-source I wouldn't recommend you to contribute to it as a first experience because its scope is very limited. There are also plenty of underfunded/undermaintained open-source projects that would benefit from your help more than this one because we have people paid to work on this.

If I may add, if you're looking for a project to contribute to, first find a project that you personally find exciting and interesting, it will greatly improve your contributions quality and your own pleasure. Also don't be afraid to contribute to projects in which you have no experience (eg outside the MERN stack), you'll learn a lot from them.

Here are a couple links to find projects:
 - https://github.com/MunGell/awesome-for-beginners : good first issues
 - https://adoptoposs.org/explore : orphan projects looking for a maintainer

**Comment by arnab15** [comment]
thanks, @romgrk for your kind suggestions. I hope I'll be find some project where I can contribute.
